use crate::config::Config;
use crate::workspace::Workspace;
use anyhow::{Context, Result};
use git2::{ObjectType, Oid, Repository, Signature};
use std::path::Path;

/// The shadow repo lives in .ortak/shadow with its worktree pointed at the
/// workspace root via core.worktree, so it coexists with the project's real
/// .git without writing any gitlink into the workspace.
pub fn init(ws: &Workspace, cfg: &Config) -> Result<Repository> {
    let mut opts = git2::RepositoryInitOptions::new();
    opts.bare(true);
    let repo = Repository::init_opts(&ws.shadow_dir, &opts).with_context(|| {
        format!(
            "could not create shadow repository: {}",
            ws.shadow_dir.display()
        )
    })?;
    {
        let mut config = repo.config()?;
        config.set_bool("core.bare", false)?;
        config.set_str("core.worktree", &ws.root.to_string_lossy())?;
    }
    write_excludes(ws, cfg)?;
    repo.set_workdir(&ws.root, false)?;
    Ok(repo)
}

pub fn open(ws: &Workspace) -> Result<Repository> {
    let repo = Repository::open(&ws.shadow_dir)
        .with_context(|| "could not open shadow repository; run `ortak init` first")?;
    // Re-seed the ignore list instead of trusting what init left behind.
    // `ortak init` returns early on an existing workspace, so someone who adds a
    // pattern to .git/info/exclude afterwards has no other way to make it count;
    // this way the next daemon start picks it up.
    write_excludes(ws, &Config::load(&ws.config_path)?)?;
    repo.set_workdir(&ws.root, false)?;
    Ok(repo)
}

fn write_excludes(ws: &Workspace, cfg: &Config) -> Result<()> {
    let info = ws.shadow_dir.join("info");
    std::fs::create_dir_all(&info)?;
    let mut lines = vec![
        "# generated by ortak".to_string(),
        ".ortak/".to_string(),
        ".git/".to_string(),
        "ortak.toml".to_string(),
        // Without these, a project that has no .gitignore gets its dependency
        // and build directories journaled, and re-committed to the shadow repo
        // on every save. [workspace] ignore is appended below, so `!target/`
        // and the like can put one back.
        "node_modules/".to_string(),
        "target/".to_string(),
        "__pycache__/".to_string(),
        ".venv/".to_string(),
        "venv/".to_string(),
    ];
    // The project's own per-clone ignore list. Someone who puts a file there
    // means "this never leaves my machine", and the shadow repo has to agree, or
    // ortak journals it and `ortak publish` ships it in the branch.
    if let Ok(local) = std::fs::read_to_string(ws.root.join(".git/info/exclude")) {
        lines.push("# from .git/info/exclude".to_string());
        lines.extend(local.lines().map(str::to_string));
    }
    // Last, so a `!pattern` in [workspace] ignore can still put something back.
    lines.extend(cfg.workspace.ignore.iter().cloned());
    let body = lines.join("\n") + "\n";
    let path = info.join("exclude");
    // Only on a change: `open` runs this on every daemon start, and rewriting the
    // file under a running daemon's ignore checks invites a torn read.
    if std::fs::read_to_string(&path).ok().as_deref() != Some(body.as_str()) {
        std::fs::write(&path, body)?;
    }
    Ok(())
}

fn head_commit(repo: &Repository) -> Option<git2::Commit<'_>> {
    repo.head().ok().and_then(|h| h.peel_to_commit().ok())
}

/// The file's blob at shadow HEAD, if tracked.
pub fn head_blob<'r>(repo: &'r Repository, rel: &str) -> Option<git2::Blob<'r>> {
    let commit = head_commit(repo)?;
    let entry = commit.tree().ok()?.get_path(Path::new(rel)).ok()?;
    repo.find_blob(entry.id()).ok()
}

/// Exact changed line ranges (zero context) between the shadow HEAD version
/// and the on-disk content. Binary or otherwise hunk-less changes fall back
/// to a conservative whole-file hunk.
pub fn compute_hunks(
    old_blob: Option<&git2::Blob<'_>>,
    new_data: Option<&[u8]>,
) -> Result<Vec<crate::regions::Hunk>> {
    let mut opts = git2::DiffOptions::new();
    opts.context_lines(0);
    let old: &[u8] = old_blob.map(|b| b.content()).unwrap_or(b"");
    let new: &[u8] = new_data.unwrap_or(b"");
    let patch = git2::Patch::from_buffers(old, None, new, None, Some(&mut opts))?;
    let mut hunks = Vec::new();
    for i in 0..patch.num_hunks() {
        let (h, _) = patch.hunk(i)?;
        hunks.push(crate::regions::Hunk {
            old_start: h.old_start() as i64,
            old_lines: h.old_lines() as i64,
            new_start: h.new_start() as i64,
            new_lines: h.new_lines() as i64,
        });
    }
    if hunks.is_empty() {
        hunks.push(crate::regions::Hunk {
            old_start: 1,
            old_lines: crate::regions::WHOLE_FILE,
            new_start: 1,
            new_lines: crate::regions::WHOLE_FILE,
        });
    }
    Ok(hunks)
}

/// Snapshot the entire current workspace as the baseline commit.
pub fn baseline(repo: &Repository) -> Result<Oid> {
    let mut index = repo.index()?;
    index.add_all(["*"].iter(), git2::IndexAddOption::DEFAULT, None)?;
    index.write()?;
    let tree_id = index.write_tree()?;
    let tree = repo.find_tree(tree_id)?;
    let sig = Signature::now("ortak", "daemon@ortak.local")?;
    let oid = repo.commit(Some("HEAD"), &sig, &sig, "baseline", &tree, &[])?;
    Ok(oid)
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Change {
    Create,
    Modify,
    Delete,
    /// Nothing to record (unchanged content, or unknown path vanished).
    None,
}

impl Change {
    pub fn as_str(&self) -> &'static str {
        match self {
            Change::Create => "create",
            Change::Modify => "modify",
            Change::Delete => "delete",
            Change::None => "none",
        }
    }
}

/// Decide what actually changed for `rel`, comparing disk state to shadow HEAD.
pub fn classify(repo: &Repository, root: &Path, rel: &str) -> Result<Change> {
    let abs = root.join(rel);
    let head_entry = head_commit(repo)
        .and_then(|c| c.tree().ok())
        .and_then(|t| t.get_path(Path::new(rel)).ok());
    let on_disk = abs.is_file();
    match (on_disk, head_entry) {
        (false, None) => Ok(Change::None),
        (false, Some(_)) => Ok(Change::Delete),
        (true, None) => Ok(Change::Create),
        (true, Some(entry)) => {
            let data = std::fs::read(&abs)?;
            let new_id = Oid::hash_object(ObjectType::Blob, &data)?;
            if new_id == entry.id() {
                Ok(Change::None)
            } else {
                Ok(Change::Modify)
            }
        }
    }
}

/// What a recorded snapshot changed, relative to shadow HEAD. The disk-based
/// `classify` cannot answer this: by the time the daemon looks, the file may
/// already carry another session's write.
pub fn classify_snapshot(repo: &Repository, rel: &str, blob: Oid) -> Change {
    match head_blob(repo, rel).map(|b| b.id()) {
        Some(old) if old == blob => Change::None,
        Some(_) => Change::Modify,
        None => Change::Create,
    }
}

/// Record one file change as a micro-commit on the shadow history. Given a
/// `blob`, the commit stores that content rather than whatever is on disk now.
pub fn commit_edit(
    repo: &Repository,
    rel: &str,
    change: Change,
    agent_name: &str,
    external_id: &str,
    blob: Option<Oid>,
) -> Result<String> {
    let mut index = repo.index()?;
    // git cannot hold a file and a directory at one path, and a session that
    // flattens src/thing/mod.rs into src/thing hands the index exactly that.
    // While the directory's entries are still there `index.add` drops the blob
    // without a word, so the micro-commit recorded nothing, the journal row
    // pointed at it anyway, and the publish that came later died on a file its
    // own history did not contain. Removing entries under `rel/` is safe
    // whatever this change is: nothing else can live under a path that is
    // about to be a file, and an index with no such directory is untouched.
    let _ = index.remove_dir(Path::new(rel), 0);
    match (change, blob) {
        // Not found when the entry was the directory the line above just
        // emptied: a watcher that reports the parent rather than each child
        // brings `rm -rf src/thing` here as one path, and the removal has
        // already happened.
        (Change::Delete, _) => {
            let _ = index.remove_path(Path::new(rel));
        }
        (_, Some(id)) => {
            let size = repo.find_blob(id)?.content().len() as u32;
            // Keep whatever mode the file already has: recording a snapshot
            // must not flip the executable bit off.
            let mode = index
                .get_path(Path::new(rel), 0)
                .map(|e| e.mode)
                .unwrap_or(0o100644);
            index.add(&git2::IndexEntry {
                ctime: git2::IndexTime::new(0, 0),
                mtime: git2::IndexTime::new(0, 0),
                dev: 0,
                ino: 0,
                mode,
                uid: 0,
                gid: 0,
                file_size: size,
                id,
                flags: 0,
                flags_extended: 0,
                path: rel.as_bytes().to_vec(),
            })?
        }
        (_, None) => index.add_path(Path::new(rel))?,
    }
    index.write()?;
    let tree_id = index.write_tree()?;
    let tree = repo.find_tree(tree_id)?;
    let email = format!(
        "{}@ortak.local",
        agent_name
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
            .collect::<String>()
    );
    let sig = Signature::now(agent_name, &email)?;
    let msg = format!(
        "{}: {}\n\nOrtak-Session: {}\n",
        change.as_str(),
        rel,
        external_id
    );
    let oid = match head_commit(repo) {
        Some(parent) => repo.commit(Some("HEAD"), &sig, &sig, &msg, &tree, &[&parent])?,
        None => repo.commit(Some("HEAD"), &sig, &sig, &msg, &tree, &[])?,
    };
    Ok(oid.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A file listed in the project's own .git/info/exclude is one somebody has
    /// already said never leaves this machine. Journaling it puts it in the next
    /// published branch.
    #[test]
    fn the_projects_own_exclude_list_reaches_the_shadow_repo() {
        let dir = std::env::temp_dir().join(format!("ortak-excludes-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join(".git/info")).unwrap();
        std::fs::write(dir.join(".git/info/exclude"), "SCRATCH*\n").unwrap();

        let ws = Workspace::at(&dir);
        let repo = init(&ws, &Config::default()).unwrap();
        assert!(repo.is_path_ignored("SCRATCH.md").unwrap());
        assert!(!repo.is_path_ignored("app.py").unwrap());

        // Added after init, which is where this matters: `ortak init` returns
        // early on a workspace that already exists, so opening the repo is the
        // only thing left that can notice.
        std::fs::write(dir.join(".git/info/exclude"), "SCRATCH*\nLATER*\n").unwrap();
        let repo = open(&ws).unwrap();
        assert!(repo.is_path_ignored("LATER.txt").unwrap());

        std::fs::remove_dir_all(&dir).ok();
    }

    /// A module flattened from thing/mod.rs into a file called thing. The index
    /// still held the directory, so `add` dropped the blob without a word: the
    /// micro-commit recorded nothing, the journal row pointed at it anyway, and
    /// the publish that came later died on a file its own history did not have.
    #[test]
    fn a_file_that_replaces_a_directory_reaches_the_micro_commit() {
        let dir = std::env::temp_dir().join(format!("ortak-dirfile-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("thing")).unwrap();
        std::fs::write(dir.join("thing/mod.rs"), "pub fn go() {}\n").unwrap();
        let ws = Workspace::at(&dir);
        let repo = init(&ws, &Config::default()).unwrap();
        baseline(&repo).unwrap();

        std::fs::remove_dir_all(dir.join("thing")).unwrap();
        std::fs::write(dir.join("thing"), "pub fn go() {}\n").unwrap();
        let id = commit_edit(&repo, "thing", Change::Modify, "claude-a", "a", None).unwrap();

        let tree = repo
            .find_commit(Oid::from_str(&id).unwrap())
            .unwrap()
            .tree()
            .unwrap();
        assert!(
            tree.get_path(Path::new("thing")).is_ok(),
            "the file the session wrote is not in its own micro-commit"
        );
        assert!(
            tree.get_path(Path::new("thing/mod.rs")).is_err(),
            "and the directory it replaced is still in there beside it"
        );
        std::fs::remove_dir_all(&dir).ok();
    }
}
