use crate::config::Config;
use crate::workspace::Workspace;
use anyhow::{Context, Result};
use git2::{ObjectType, Oid, Repository, Signature};
use std::path::Path;

/// The shadow repo lives in .ortak/shadow with its worktree pointed at the
/// workspace root via core.worktree, so it coexists with the project's real
/// .git without writing any gitlink into the workspace.
pub fn init(ws: &Workspace, cfg: &Config) -> Result<Repository> {
    let mut opts = git2::RepositoryInitOptions::new();
    opts.bare(true);
    let repo = Repository::init_opts(&ws.shadow_dir, &opts).with_context(|| {
        format!(
            "could not create shadow repository: {}",
            ws.shadow_dir.display()
        )
    })?;
    {
        let mut config = repo.config()?;
        config.set_bool("core.bare", false)?;
        config.set_str("core.worktree", &ws.root.to_string_lossy())?;
    }
    write_excludes(ws, cfg)?;
    repo.set_workdir(&ws.root, false)?;
    Ok(repo)
}

pub fn open(ws: &Workspace) -> Result<Repository> {
    let repo = Repository::open(&ws.shadow_dir)
        .with_context(|| "could not open shadow repository; run `ortak init` first")?;
    // Re-seed the ignore list instead of trusting what init left behind.
    // `ortak init` returns early on an existing workspace, so someone who adds a
    // pattern to .git/info/exclude afterwards has no other way to make it count;
    // this way the next daemon start picks it up.
    write_excludes(ws, &Config::load(&ws.config_path)?)?;
    repo.set_workdir(&ws.root, false)?;
    Ok(repo)
}

/// ortak's own ignore list, as gitignore rules.
///
/// This is the one list that applies to every repository in the workspace
/// rather than to whichever one owns a path: no project's `.gitignore` mentions
/// `.ortak`, and a tree of sixty repositories has sixty of them to tell.
pub fn exclude_rules(ws: &Workspace, cfg: &Config) -> String {
    let mut lines = vec![
        "# generated by ortak".to_string(),
        ".ortak/".to_string(),
        ".git/".to_string(),
        "ortak.toml".to_string(),
        // Without these, a project that has no .gitignore gets its dependency
        // and build directories journaled, and re-committed to the shadow repo
        // on every save. [workspace] ignore is appended below, so `!target/`
        // and the like can put one back.
        "node_modules/".to_string(),
        "target/".to_string(),
        "__pycache__/".to_string(),
        ".venv/".to_string(),
        "venv/".to_string(),
    ];
    // The project's own per-clone ignore list. Someone who puts a file there
    // means "this never leaves my machine", and the shadow repo has to agree, or
    // ortak journals it and `ortak publish` ships it in the branch.
    if let Ok(local) = std::fs::read_to_string(ws.root.join(".git/info/exclude")) {
        lines.push("# from .git/info/exclude".to_string());
        lines.extend(local.lines().map(str::to_string));
    }
    // Last, so a `!pattern` in [workspace] ignore can still put something back.
    lines.extend(cfg.workspace.ignore.iter().cloned());
    lines.join("\n") + "\n"
}

fn write_excludes(ws: &Workspace, cfg: &Config) -> Result<()> {
    let info = ws.shadow_dir.join("info");
    std::fs::create_dir_all(&info)?;
    let body = exclude_rules(ws, cfg);
    let path = info.join("exclude");
    // Only on a change: `open` runs this on every daemon start, and rewriting the
    // file under a running daemon's ignore checks invites a torn read.
    if std::fs::read_to_string(&path).ok().as_deref() != Some(body.as_str()) {
        std::fs::write(&path, body)?;
    }
    Ok(())
}

/// Whether ortak leaves `rel` out of the journal.
///
/// The repository that owns the path decides. An ancestor's `.gitignore` says
/// what that repository does not track, and it has no authority over a
/// repository whose content it does not hold: `repos/` in an Odoo checkout
/// means "this checkout does not version those directories", and reading it as
/// "nobody is working in there" took sixty repositories out of the journal.
/// Where the owner is the workspace root this is the shadow repository, which
/// is what happened before and what still happens in an ordinary workspace.
///
/// ponytail: opens the owning repository on every call. The daemon asks this
/// once per debounced path, so it is a repository open per file change; cache
/// by repository directory if that ever shows up in a profile.
pub fn ignored(ws: &Workspace, shadow: &Repository, excludes: &str, rel: &str) -> bool {
    let at_root = |rel: &str| shadow.is_path_ignored(rel).unwrap_or(false);
    let Some(dir) = ws.repo_of(rel).filter(|d| !d.is_empty()) else {
        return at_root(rel);
    };
    // A repository's own root, which is a directory: nothing to ask, and
    // pruning it would take the repository with it.
    let Some(inner) = rel
        .strip_prefix(dir.as_str())
        .and_then(|r| r.strip_prefix('/'))
    else {
        return false;
    };
    let Ok(owner) = Repository::open(ws.root.join(&dir)) else {
        return at_root(rel);
    };
    if owner.add_ignore_rule(excludes).is_err() {
        return at_root(rel);
    }
    owner.is_path_ignored(inner).unwrap_or(false)
}

fn head_commit(repo: &Repository) -> Option<git2::Commit<'_>> {
    repo.head().ok().and_then(|h| h.peel_to_commit().ok())
}

/// The file's blob at shadow HEAD, if tracked.
pub fn head_blob<'r>(repo: &'r Repository, rel: &str) -> Option<git2::Blob<'r>> {
    let commit = head_commit(repo)?;
    let entry = commit.tree().ok()?.get_path(Path::new(rel)).ok()?;
    repo.find_blob(entry.id()).ok()
}

/// Exact changed line ranges (zero context) between the shadow HEAD version
/// and the on-disk content. Binary or otherwise hunk-less changes fall back
/// to a conservative whole-file hunk.
pub fn compute_hunks(
    old_blob: Option<&git2::Blob<'_>>,
    new_data: Option<&[u8]>,
) -> Result<Vec<crate::regions::Hunk>> {
    let mut opts = git2::DiffOptions::new();
    opts.context_lines(0);
    let old: &[u8] = old_blob.map(|b| b.content()).unwrap_or(b"");
    let new: &[u8] = new_data.unwrap_or(b"");
    let patch = git2::Patch::from_buffers(old, None, new, None, Some(&mut opts))?;
    let mut hunks = Vec::new();
    for i in 0..patch.num_hunks() {
        let (h, _) = patch.hunk(i)?;
        hunks.push(crate::regions::Hunk {
            old_start: h.old_start() as i64,
            old_lines: h.old_lines() as i64,
            new_start: h.new_start() as i64,
            new_lines: h.new_lines() as i64,
        });
    }
    if hunks.is_empty() {
        hunks.push(crate::regions::Hunk {
            old_start: 1,
            old_lines: crate::regions::WHOLE_FILE,
            new_start: 1,
            new_lines: crate::regions::WHOLE_FILE,
        });
    }
    Ok(hunks)
}

/// Snapshot the entire current workspace as the baseline commit.
///
/// This walks the tree rather than calling `index.add_all`, which cannot do the
/// job in a workspace holding more than one repository. libgit2's workdir
/// iterator reads a directory with a `.git` in it as a submodule and hands the
/// index `odoo-server/`, trailing slash and all, which the index refuses:
/// `invalid path: 'odoo-server/'`. A callback can skip that entry, and skipping
/// it is all it can do, because the iterator will not descend into the
/// directory either, with or without a pathspec naming it. `index.add_path` on
/// a file inside such a directory works perfectly well, so the walk is what is
/// left, and it asks the same `ignored` the daemon asks.
///
/// The baseline matters more than it looks: without a shadow entry for a file,
/// the first touch classifies as a create and produces one whole-file hunk, so
/// a session that edits one line of a 4000-line model claims all 4000 and the
/// gate locks everybody else out of the file.
/// Returns the commit, and every path the walk could not read. One file it
/// cannot open used to fail the whole baseline, and the workspace was then left
/// with a database, a shadow repository with no HEAD and no way back: the
/// repair on the next `init` reaches the same file and fails the same way,
/// every time. A tree that holds sixty repositories holds logs, backups and
/// filestores too, some of them another user's.
pub fn baseline(repo: &Repository, ws: &Workspace, cfg: &Config) -> Result<(Oid, Vec<String>)> {
    let excludes = exclude_rules(ws, cfg);
    let mut index = repo.index()?;
    let mut unread = Vec::new();
    add_tree(&mut index, repo, ws, &excludes, "", &mut unread)?;
    index.write()?;
    let tree_id = index.write_tree()?;
    let tree = repo.find_tree(tree_id)?;
    let sig = Signature::now("ortak", "daemon@ortak.local")?;
    let oid = repo.commit(Some("HEAD"), &sig, &sig, "baseline", &tree, &[])?;
    unread.sort();
    Ok((oid, unread))
}

/// Add every file under one workspace-relative directory to the index, deciding
/// each one the way the daemon will, and collecting what could not be read.
fn add_tree(
    index: &mut git2::Index,
    repo: &Repository,
    ws: &Workspace,
    excludes: &str,
    rel: &str,
    unread: &mut Vec<String>,
) -> Result<()> {
    let Ok(entries) = std::fs::read_dir(ws.root.join(rel)) else {
        // A directory this process cannot open. Nothing under it reaches the
        // baseline, which is worth one line rather than silence.
        if !rel.is_empty() {
            unread.push(format!("{rel}/"));
        }
        return Ok(());
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        // At any depth, and before the ignore question: a repository does not
        // ignore its own `.git`, so once the owning repository is the one
        // answering, every nested `.git/index` is a journalable path.
        if name == ".git" || name == crate::workspace::ORTAK_DIR {
            continue;
        }
        let path = entry.path();
        let Some(child) = ws.relativize(&path) else {
            continue;
        };
        let Ok(kind) = entry.file_type() else {
            continue;
        };
        if kind.is_dir() {
            if ignored(ws, repo, excludes, &child) && !hides_a_repository(&path) {
                continue;
            }
            add_tree(index, repo, ws, excludes, &child, unread)?;
        // A symlink is a file here whatever it points at, which is what
        // `add_all` does with one and what keeps this walk out of a loop.
        } else if (kind.is_file() || kind.is_symlink()) && !ignored(ws, repo, excludes, &child) {
            // A file ortak cannot read is a file it cannot journal either, so
            // it is the caller's business rather than an error: one `chmod 000`
            // anywhere in the tree used to cost the workspace its whole
            // baseline. This also covers a file that went away between the
            // directory listing and here, which is a build running during
            // `init`.
            if index.add_path(Path::new(&child)).is_err() {
                unread.push(child);
            }
        }
        // Anything left is a fifo, a socket or a device node. git has no way to
        // store one and `add_all` passed over them without a word; `add_path`
        // opens what it is given, so on a fifo with no writer it blocks for as
        // long as the machine is up. A socket in `tmp/` is enough to make
        // `ortak init` never return.
    }
    Ok(())
}

/// Whether an ignored directory has to be walked anyway. `repos/` is ignored in
/// the checkout this was written for and the sixty repositories under it are the
/// whole point, so a directory the root does not track can still hold work that
/// belongs to somebody.
///
/// ponytail: one level down. A repository buried deeper inside an ignored
/// directory is not found, and the fix is to walk further here.
fn hides_a_repository(dir: &Path) -> bool {
    std::fs::read_dir(dir)
        .is_ok_and(|mut entries| entries.any(|e| e.is_ok_and(|e| e.path().join(".git").exists())))
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Change {
    Create,
    Modify,
    Delete,
    /// Nothing to record (unchanged content, or unknown path vanished).
    None,
}

impl Change {
    pub fn as_str(&self) -> &'static str {
        match self {
            Change::Create => "create",
            Change::Modify => "modify",
            Change::Delete => "delete",
            Change::None => "none",
        }
    }
}

/// Decide what actually changed for `rel`, comparing disk state to shadow HEAD.
pub fn classify(repo: &Repository, root: &Path, rel: &str) -> Result<Change> {
    let abs = root.join(rel);
    let head_entry = head_commit(repo)
        .and_then(|c| c.tree().ok())
        .and_then(|t| t.get_path(Path::new(rel)).ok());
    let on_disk = abs.is_file();
    match (on_disk, head_entry) {
        (false, None) => Ok(Change::None),
        (false, Some(_)) => Ok(Change::Delete),
        (true, None) => Ok(Change::Create),
        (true, Some(entry)) => {
            let data = std::fs::read(&abs)?;
            let new_id = Oid::hash_object(ObjectType::Blob, &data)?;
            if new_id == entry.id() {
                Ok(Change::None)
            } else {
                Ok(Change::Modify)
            }
        }
    }
}

/// What a recorded snapshot changed, relative to shadow HEAD. The disk-based
/// `classify` cannot answer this: by the time the daemon looks, the file may
/// already carry another session's write.
pub fn classify_snapshot(repo: &Repository, rel: &str, blob: Oid) -> Change {
    match head_blob(repo, rel).map(|b| b.id()) {
        Some(old) if old == blob => Change::None,
        Some(_) => Change::Modify,
        None => Change::Create,
    }
}

/// Record one file change as a micro-commit on the shadow history. Given a
/// `blob`, the commit stores that content rather than whatever is on disk now.
pub fn commit_edit(
    repo: &Repository,
    rel: &str,
    change: Change,
    agent_name: &str,
    external_id: &str,
    blob: Option<Oid>,
) -> Result<String> {
    let mut index = repo.index()?;
    // git cannot hold a file and a directory at one path, and a session that
    // flattens src/thing/mod.rs into src/thing hands the index exactly that.
    // While the directory's entries are still there `index.add` drops the blob
    // without a word, so the micro-commit recorded nothing, the journal row
    // pointed at it anyway, and the publish that came later died on a file its
    // own history did not contain. Removing entries under `rel/` is safe
    // whatever this change is: nothing else can live under a path that is
    // about to be a file, and an index with no such directory is untouched.
    let _ = index.remove_dir(Path::new(rel), 0);
    match (change, blob) {
        // Not found when the entry was the directory the line above just
        // emptied: a watcher that reports the parent rather than each child
        // brings `rm -rf src/thing` here as one path, and the removal has
        // already happened.
        (Change::Delete, _) => {
            let _ = index.remove_path(Path::new(rel));
        }
        (_, Some(id)) => {
            let size = repo.find_blob(id)?.content().len() as u32;
            // Keep whatever mode the file already has: recording a snapshot
            // must not flip the executable bit off.
            let mode = index
                .get_path(Path::new(rel), 0)
                .map(|e| e.mode)
                .unwrap_or(0o100644);
            index.add(&git2::IndexEntry {
                ctime: git2::IndexTime::new(0, 0),
                mtime: git2::IndexTime::new(0, 0),
                dev: 0,
                ino: 0,
                mode,
                uid: 0,
                gid: 0,
                file_size: size,
                id,
                flags: 0,
                flags_extended: 0,
                path: rel.as_bytes().to_vec(),
            })?
        }
        (_, None) => index.add_path(Path::new(rel))?,
    }
    index.write()?;
    let tree_id = index.write_tree()?;
    let tree = repo.find_tree(tree_id)?;
    let email = format!(
        "{}@ortak.local",
        agent_name
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
            .collect::<String>()
    );
    let sig = Signature::now(agent_name, &email)?;
    let msg = format!(
        "{}: {}\n\nOrtak-Session: {}\n",
        change.as_str(),
        rel,
        external_id
    );
    let oid = match head_commit(repo) {
        Some(parent) => repo.commit(Some("HEAD"), &sig, &sig, &msg, &tree, &[&parent])?,
        None => repo.commit(Some("HEAD"), &sig, &sig, &msg, &tree, &[])?,
    };
    Ok(oid.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A file listed in the project's own .git/info/exclude is one somebody has
    /// already said never leaves this machine. Journaling it puts it in the next
    /// published branch.
    #[test]
    fn the_projects_own_exclude_list_reaches_the_shadow_repo() {
        let dir = std::env::temp_dir().join(format!("ortak-excludes-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join(".git/info")).unwrap();
        std::fs::write(dir.join(".git/info/exclude"), "SCRATCH*\n").unwrap();

        let ws = Workspace::at(&dir);
        let repo = init(&ws, &Config::default()).unwrap();
        assert!(repo.is_path_ignored("SCRATCH.md").unwrap());
        assert!(!repo.is_path_ignored("app.py").unwrap());

        // Added after init, which is where this matters: `ortak init` returns
        // early on a workspace that already exists, so opening the repo is the
        // only thing left that can notice.
        std::fs::write(dir.join(".git/info/exclude"), "SCRATCH*\nLATER*\n").unwrap();
        let repo = open(&ws).unwrap();
        assert!(repo.is_path_ignored("LATER.txt").unwrap());

        std::fs::remove_dir_all(&dir).ok();
    }

    /// A module flattened from thing/mod.rs into a file called thing. The index
    /// still held the directory, so `add` dropped the blob without a word: the
    /// micro-commit recorded nothing, the journal row pointed at it anyway, and
    /// the publish that came later died on a file its own history did not have.
    #[test]
    fn a_file_that_replaces_a_directory_reaches_the_micro_commit() {
        let dir = std::env::temp_dir().join(format!("ortak-dirfile-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("thing")).unwrap();
        std::fs::write(dir.join("thing/mod.rs"), "pub fn go() {}\n").unwrap();
        let ws = Workspace::at(&dir);
        let cfg = Config::default();
        let repo = init(&ws, &cfg).unwrap();
        baseline(&repo, &ws, &cfg).unwrap();

        std::fs::remove_dir_all(dir.join("thing")).unwrap();
        std::fs::write(dir.join("thing"), "pub fn go() {}\n").unwrap();
        let id = commit_edit(&repo, "thing", Change::Modify, "claude-a", "a", None).unwrap();

        let tree = repo
            .find_commit(Oid::from_str(&id).unwrap())
            .unwrap()
            .tree()
            .unwrap();
        assert!(
            tree.get_path(Path::new("thing")).is_ok(),
            "the file the session wrote is not in its own micro-commit"
        );
        assert!(
            tree.get_path(Path::new("thing/mod.rs")).is_err(),
            "and the directory it replaced is still in there beside it"
        );
        std::fs::remove_dir_all(&dir).ok();
    }

    /// A workspace whose tree holds a repository of its own. The root's
    /// `.gitignore` says `repos/`, which is a checkout saying it does not
    /// version those directories, and it was being read as nobody working in
    /// there. The baseline could not be captured at all either: libgit2 reads a
    /// directory holding a `.git` as a submodule and hands the index
    /// `repos/inner/`, which the index refuses.
    #[test]
    fn the_baseline_covers_a_repository_the_root_ignores() {
        let dir = std::env::temp_dir().join(format!("ortak-nested-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("addons")).unwrap();
        std::fs::create_dir_all(dir.join("repos/inner/models")).unwrap();
        std::fs::create_dir_all(dir.join("build")).unwrap();
        std::fs::create_dir_all(dir.join("target")).unwrap();
        std::fs::write(dir.join(".gitignore"), "repos/\nbuild/\n").unwrap();
        std::fs::write(dir.join("addons/a.py"), "a = 1\n").unwrap();
        std::fs::write(dir.join("build/junk.o"), "junk\n").unwrap();
        std::fs::write(dir.join("target/junk.o"), "junk\n").unwrap();
        std::fs::write(dir.join("repos/inner/.gitignore"), "*.pyc\n").unwrap();
        std::fs::write(dir.join("repos/inner/models/sale.py"), "y = 1\n").unwrap();
        std::fs::write(dir.join("repos/inner/models/sale.pyc"), "compiled\n").unwrap();
        git2::Repository::init(&dir).unwrap();
        git2::Repository::init(dir.join("repos/inner")).unwrap();
        // A named pipe, which git cannot store and `index.add_path` opens: with
        // no writer on the other end, adding it never returns. A project with a
        // socket in `tmp/` is enough, so if this test ever hangs, that is why.
        let fifo = std::ffi::CString::new(dir.join("addons/queue.sock").to_str().unwrap()).unwrap();
        assert_eq!(unsafe { libc::mkfifo(fifo.as_ptr(), 0o644) }, 0);

        let ws = Workspace::at(&dir);
        let cfg = Config::default();
        let repo = init(&ws, &cfg).unwrap();
        let excludes = exclude_rules(&ws, &cfg);

        // Each repository answers for its own files: the nested one keeps its
        // source and drops its own build output, and the root keeps deciding
        // everything that is actually its.
        assert!(!ignored(
            &ws,
            &repo,
            &excludes,
            "repos/inner/models/sale.py"
        ));
        assert!(ignored(
            &ws,
            &repo,
            &excludes,
            "repos/inner/models/sale.pyc"
        ));
        assert!(ignored(&ws, &repo, &excludes, "build/junk.o"));
        assert!(ignored(&ws, &repo, &excludes, "target/junk.o"));

        // One unreadable file, which used to fail the whole baseline and leave
        // the workspace with none at all.
        std::fs::write(dir.join("addons/locked.py"), "secret = 1\n").unwrap();
        let mut perms = std::fs::metadata(dir.join("addons/locked.py"))
            .unwrap()
            .permissions();
        std::os::unix::fs::PermissionsExt::set_mode(&mut perms, 0o000);
        std::fs::set_permissions(dir.join("addons/locked.py"), perms).unwrap();

        let (oid, unread) = baseline(&repo, &ws, &cfg).unwrap();
        assert_eq!(unread, ["addons/locked.py"]);
        let mut paths = Vec::new();
        repo.find_commit(oid)
            .unwrap()
            .tree()
            .unwrap()
            .walk(git2::TreeWalkMode::PreOrder, |root, entry| {
                if entry.kind() == Some(ObjectType::Blob) {
                    paths.push(format!("{}{}", root, entry.name().unwrap_or("")));
                }
                git2::TreeWalkResult::Ok
            })
            .unwrap();
        paths.sort();
        assert_eq!(
            paths,
            [
                ".gitignore",
                "addons/a.py",
                "repos/inner/.gitignore",
                "repos/inner/models/sale.py",
            ]
        );
        std::fs::remove_dir_all(&dir).ok();
    }
}
