use crate::config::Config;
use crate::workspace::Workspace;
use anyhow::{Context, Result};
use git2::{ObjectType, Oid, Repository, Signature};
use std::path::Path;

/// The shadow repo lives in .ortak/shadow with its worktree pointed at the
/// workspace root via core.worktree, so it coexists with the project's real
/// .git without writing any gitlink into the workspace.
pub fn init(ws: &Workspace, cfg: &Config) -> Result<Repository> {
    let mut opts = git2::RepositoryInitOptions::new();
    opts.bare(true);
    let repo = Repository::init_opts(&ws.shadow_dir, &opts).with_context(|| {
        format!(
            "could not create shadow repository: {}",
            ws.shadow_dir.display()
        )
    })?;
    {
        let mut config = repo.config()?;
        config.set_bool("core.bare", false)?;
        config.set_str("core.worktree", &ws.root.to_string_lossy())?;
    }
    write_excludes(ws, cfg)?;
    repo.set_workdir(&ws.root, false)?;
    Ok(repo)
}

pub fn open(ws: &Workspace) -> Result<Repository> {
    let repo = Repository::open(&ws.shadow_dir)
        .with_context(|| "could not open shadow repository; run `ortak init` first")?;
    repo.set_workdir(&ws.root, false)?;
    Ok(repo)
}

fn write_excludes(ws: &Workspace, cfg: &Config) -> Result<()> {
    let info = ws.shadow_dir.join("info");
    std::fs::create_dir_all(&info)?;
    let mut lines = vec![
        "# generated by ortak".to_string(),
        ".ortak/".to_string(),
        ".git/".to_string(),
        "ortak.toml".to_string(),
    ];
    lines.extend(cfg.workspace.ignore.iter().cloned());
    std::fs::write(info.join("exclude"), lines.join("\n") + "\n")?;
    Ok(())
}

fn head_commit(repo: &Repository) -> Option<git2::Commit<'_>> {
    repo.head().ok().and_then(|h| h.peel_to_commit().ok())
}

/// The file's blob at shadow HEAD, if tracked.
pub fn head_blob<'r>(repo: &'r Repository, rel: &str) -> Option<git2::Blob<'r>> {
    let commit = head_commit(repo)?;
    let entry = commit.tree().ok()?.get_path(Path::new(rel)).ok()?;
    repo.find_blob(entry.id()).ok()
}

/// Exact changed line ranges (zero context) between the shadow HEAD version
/// and the on-disk content. Binary or otherwise hunk-less changes fall back
/// to a conservative whole-file hunk.
pub fn compute_hunks(
    old_blob: Option<&git2::Blob<'_>>,
    new_data: Option<&[u8]>,
) -> Result<Vec<crate::regions::Hunk>> {
    let mut opts = git2::DiffOptions::new();
    opts.context_lines(0);
    let old: &[u8] = old_blob.map(|b| b.content()).unwrap_or(b"");
    let new: &[u8] = new_data.unwrap_or(b"");
    let patch = git2::Patch::from_buffers(old, None, new, None, Some(&mut opts))?;
    let mut hunks = Vec::new();
    for i in 0..patch.num_hunks() {
        let (h, _) = patch.hunk(i)?;
        hunks.push(crate::regions::Hunk {
            old_start: h.old_start() as i64,
            old_lines: h.old_lines() as i64,
            new_start: h.new_start() as i64,
            new_lines: h.new_lines() as i64,
        });
    }
    if hunks.is_empty() {
        hunks.push(crate::regions::Hunk {
            old_start: 1,
            old_lines: crate::regions::WHOLE_FILE,
            new_start: 1,
            new_lines: crate::regions::WHOLE_FILE,
        });
    }
    Ok(hunks)
}

/// Snapshot the entire current workspace as the baseline commit.
pub fn baseline(repo: &Repository) -> Result<Oid> {
    let mut index = repo.index()?;
    index.add_all(["*"].iter(), git2::IndexAddOption::DEFAULT, None)?;
    index.write()?;
    let tree_id = index.write_tree()?;
    let tree = repo.find_tree(tree_id)?;
    let sig = Signature::now("ortak", "daemon@ortak.local")?;
    let oid = repo.commit(Some("HEAD"), &sig, &sig, "baseline", &tree, &[])?;
    Ok(oid)
}

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Change {
    Create,
    Modify,
    Delete,
    /// Nothing to record (unchanged content, or unknown path vanished).
    None,
}

impl Change {
    pub fn as_str(&self) -> &'static str {
        match self {
            Change::Create => "create",
            Change::Modify => "modify",
            Change::Delete => "delete",
            Change::None => "none",
        }
    }
}

/// Decide what actually changed for `rel`, comparing disk state to shadow HEAD.
pub fn classify(repo: &Repository, root: &Path, rel: &str) -> Result<Change> {
    let abs = root.join(rel);
    let head_entry = head_commit(repo)
        .and_then(|c| c.tree().ok())
        .and_then(|t| t.get_path(Path::new(rel)).ok());
    let on_disk = abs.is_file();
    match (on_disk, head_entry) {
        (false, None) => Ok(Change::None),
        (false, Some(_)) => Ok(Change::Delete),
        (true, None) => Ok(Change::Create),
        (true, Some(entry)) => {
            let data = std::fs::read(&abs)?;
            let new_id = Oid::hash_object(ObjectType::Blob, &data)?;
            if new_id == entry.id() {
                Ok(Change::None)
            } else {
                Ok(Change::Modify)
            }
        }
    }
}

/// Record one file change as a micro-commit on the shadow history.
pub fn commit_edit(
    repo: &Repository,
    rel: &str,
    change: Change,
    agent_name: &str,
    external_id: &str,
) -> Result<String> {
    let mut index = repo.index()?;
    match change {
        Change::Delete => index.remove_path(Path::new(rel))?,
        _ => index.add_path(Path::new(rel))?,
    }
    index.write()?;
    let tree_id = index.write_tree()?;
    let tree = repo.find_tree(tree_id)?;
    let email = format!(
        "{}@ortak.local",
        agent_name
            .chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
            .collect::<String>()
    );
    let sig = Signature::now(agent_name, &email)?;
    let msg = format!(
        "{}: {}\n\nOrtak-Session: {}\n",
        change.as_str(),
        rel,
        external_id
    );
    let oid = match head_commit(repo) {
        Some(parent) => repo.commit(Some("HEAD"), &sig, &sig, &msg, &tree, &[&parent])?,
        None => repo.commit(Some("HEAD"), &sig, &sig, &msg, &tree, &[])?,
    };
    Ok(oid.to_string())
}
